const Product = require("./model/product");

const arr = [
  {
    name: "Smartphone XYZ",
    images: [
      "https://img.freepik.com/free-vector/modern-wave-background-smartphone_23-2147574229.jpg",
      "https://img.freepik.com/free-vector/wavy-abstract-background-smartphone_23-2147574231.jpg",
      "https://img.freepik.com/free-vector/wave-abstract-background-with-smartphone_23-2147574232.jpg",
    ],
    price: 14999,
    originalPrice: 19999,
    rating: 4.5,

    description: "A powerful smartphone with the latest technology.",
    highlights: ["4GB RAM", "128GB Storage", "5000mAh Battery", "Dual SIM"],
    features: [
      "Octa-core Processor",
      "Super AMOLED Display",
      "Fast Charging",
      "5G Support",
    ],
    category: "Electronics",
  },
  {
    name: "Bluetooth Headphones ABC",
    images: [
      "https://img.freepik.com/free-photo/headphones-with-minimalist-monochrome-background_23-2150763311.jpg",
      "https://img.freepik.com/free-psd/technological-headphones-isolated_23-2151209615.jpg",
      "https://img.freepik.com/free-photo/headphones-with-minimalist-monochrome-background_23-2150763316.jpg",
    ],
    price: 1999,
    originalPrice: 2499,
    rating: 4.2,

    description:
      "Wireless headphones with superior sound and noise cancellation.",
    highlights: ["Noise Cancellation", "20 Hours Playback", "Bluetooth 5.0"],
    features: [
      "Over-ear Design",
      "Built-in Microphone",
      "Fast Charging",
      "Multipoint Connection",
    ],
    category: "Audio",
  },
  {
    name: "Smart TV DEF",
    images: [
      "https://img.freepik.com/free-photo/tv-with-city-skyline-illuminated-dusk-with-traffic-motion-generative-ai_188544-19469.jpg",
      "https://img.freepik.com/free-psd/modern-tv-isolated_23-2151430326.jpg",
      "https://img.freepik.com/free-photo/television-houseplants-room-scene-generative-ai_188544-12145.jpg",
    ],
    price: 24999,
    originalPrice: 29999,
    rating: 4.7,

    description: "A 4K Smart TV with crystal-clear display and Dolby audio.",
    highlights: ["4K UHD", "HDR10+", "Smart Features", "50-inch Display"],
    features: [
      "Built-in Chromecast",
      "Voice Assistant",
      "3 HDMI Ports",
      "Dolby Vision",
    ],
    category: "Home Entertainment",
  },
  {
    name: "Smartwatch GHI",
    images: [
      "https://img.freepik.com/free-photo/smartwatch-with-digital-assistant-arrangement_23-2149108009.jpg",
      "https://img.freepik.com/free-vector/fitness-trackers-concept_23-2148529803.jpg",
      "https://img.freepik.com/free-vector/smart-watch-cartoon-vector-icon-illustration-technology-object-icon-isolated-flat-vector_138676-13479.jpg",
    ],
    price: 4499,
    originalPrice: 5999,
    rating: 4.3,

    description: "A fitness smartwatch with heart rate monitoring and GPS.",
    highlights: ["Heart Rate Monitor", "GPS", "1.4-inch Display", "Waterproof"],
    features: ["Customizable Watch Faces", "Music Control", "Step Tracking"],
    category: "Wearables",
  },
  {
    name: "Laptop JKL",
    images: [
      "https://img.freepik.com/free-vector/notebook-with-social-media-icon-theme-hands-isolated-white-background_1308-44904.jpg",
      "https://img.freepik.com/free-vector/laptop-with-education-icon-isolated_1308-48315.jpg",
      "https://img.freepik.com/free-photo/laptop-with-blank-white-screen-books-eyeglasses-pencil-holders-paperclip-wooden-desk_23-2147979131.jpg",
    ],
    price: 49999,
    originalPrice: 54999,
    rating: 4.6,

    description:
      "A high-performance laptop for work, gaming, and entertainment.",
    highlights: [
      "16GB RAM",
      "512GB SSD",
      "Intel i7 Processor",
      "15.6-inch Display",
    ],
    features: ["Backlit Keyboard", "Wi-Fi 6", "Thunderbolt 3", "Slim Design"],
    category: "Computers",
  },
  {
    name: "Smart Door Lock MNO",
    images: [
      "https://img.freepik.com/free-photo/scanning-finger-coronavirus-contaminated-fingerprint-access-control_53876-95279.jpg",
      "https://img.freepik.com/free-photo/intercom-main-gate-residential-building_637285-1929.jpg",
      "https://img.freepik.com/premium-vector/door-lock_1083548-13329.jpg?w=740",
    ],
    price: 8499,
    originalPrice: 9999,
    rating: 4.4,

    description: "A secure smart door lock with fingerprint and app control.",
    highlights: ["Fingerprint Sensor", "App Control", "Tamper Alarm"],
    features: ["Auto Lock", "Remote Unlock", "Emergency Battery Backup"],
    category: "Smart Home",
  },
  {
    name: "Gaming Chair PQR",
    images: [
      "https://img.freepik.com/free-photo/still-life-seat-gamers_23-2149746592.jpg",
      "https://img.freepik.com/premium-photo/modern-comfortable-chair-designer-isolated-white-background_985092-5961.jpg?w=740",
      "https://img.freepik.com/free-photo/still-life-seat-gamers_23-2149746572.jpg",
    ],
    price: 10999,
    originalPrice: 12999,
    rating: 4.5,

    description:
      "An ergonomic gaming chair designed for comfort during long sessions.",
    highlights: [
      "Reclining Backrest",
      "Adjustable Armrests",
      "Memory Foam Padding",
    ],
    features: ["360-degree Swivel", "Lumbar Support", "Leather Finish"],
    category: "Furniture",
  },
  {
    name: "Blender STU",
    images: [
      "https://img.freepik.com/free-vector/flat-smoothies-blender-glass-illustration_23-2148948634.jpg",
      "https://img.freepik.com/free-vector/realistic-smoothies-blender-glass-illustration_52683-62066.jpg",
      "https://img.freepik.com/free-vector/flat-smoothies-blender-glass-illustration_23-2148956218.jpg",
    ],
    price: 2199,
    originalPrice: 2999,
    rating: 4.3,

    description: "A versatile blender perfect for smoothies, sauces, and more.",
    highlights: ["500W Power", "2 Speed Settings", "Multi-Purpose Blades"],
    features: ["BPA-Free Jar", "Dishwasher Safe", "Compact Design"],
    category: "Kitchen Appliances",
  },
  {
    name: "Air Purifier VWX",
    images: [
      "https://img.freepik.com/free-photo/young-woman-using-home-technology_23-2149216656.jpg",
      "https://img.freepik.com/free-vector/realistic-digital-air-purifier-floor-cozy-room-vector-illustration_1284-70561.jpg",
      "https://img.freepik.com/free-vector/modern-air-purifier-removing-dust-cleaning-air-living-room-sofa-realistic-vector-illustration_1284-68359.jpg",
    ],
    price: 9999,
    originalPrice: 12499,
    rating: 4.7,

    description: "An air purifier with HEPA filter for clean and fresh air.",
    highlights: ["HEPA Filter", "Auto Mode", "Silent Operation"],
    features: [
      "Real-Time Air Quality Indicator",
      "Filter Replacement Alerts",
      "Sleep Mode",
    ],
    category: "Home Appliances",
  },
  {
    name: "Coffee Maker XYZ",
    images: [
      "https://img.freepik.com/free-vector/cooking-utensils_24911-45039.jpg",
      "https://img.freepik.com/free-photo/view-process-making-pressed-coffee_23-2149709946.jpg",
      "https://img.freepik.com/free-photo/view-coffee-making-machine_23-2150698665.jpg",
    ],
    price: 4299,
    originalPrice: 5499,
    rating: 4.4,

    description: "A compact coffee maker with programmable brewing options.",
    highlights: ["1.2L Capacity", "Programmable Timer", "Auto Shut-off"],
    features: [
      "Removable Water Tank",
      "Brew Strength Selector",
      "Keep Warm Function",
    ],
    category: "Kitchen Appliances",
  },
  {
    name: "Smart Light Bulb ABC",
    images: [
      "https://img.freepik.com/free-vector/infographics-with-light-bulb-flat-design_23-2147790217.jpg",
      "https://img.freepik.com/free-vector/letter-l-lightbulb_1308-84273.jpg",
      "https://img.freepik.com/free-vector/glowing-light-bulb-infographic_23-2147505352.jpg",
    ],
    price: 899,
    originalPrice: 1199,
    rating: 4.6,

    description:
      "A smart light bulb with customizable colors and voice control.",
    highlights: [
      "16 Million Colors",
      "App Control",
      "Voice Assistant Compatible",
    ],
    features: ["Energy Efficient", "Dimmable", "Schedules and Timers"],
    category: "Smart Home",
  },
  {
    name: "Electric Kettle DEF",
    images: [
      "https://img.freepik.com/free-photo/close-up-air-fryer_23-2151723487.jpg",
      "https://img.freepik.com/free-photo/close-up-air-fryer_23-2151723471.jpg",
      "https://img.freepik.com/free-photo/coffee-cup-green-garden_1150-14525.jpg",
    ],
    price: 1499,
    originalPrice: 1999,
    rating: 4.3,

    description: "A stainless steel electric kettle for fast boiling.",
    highlights: ["1.7L Capacity", "Auto Shut-off", "Boil-Dry Protection"],
    features: [
      "Cordless Operation",
      "360-degree Swivel Base",
      "Water Level Indicator",
    ],
    category: "Kitchen Appliances",
  },
  {
    name: "Fitness Tracker GHI",
    images: [
      "https://img.freepik.com/free-vector/flat-design-apps-fitness-tracker-man-running_23-2148527078.jpg",
      "https://img.freepik.com/free-vector/smartwatch-concept-illustration_114360-4306.jpg",
      "https://img.freepik.com/free-vector/fitness-trackers-flat-design_23-2148542402.jpg",
    ],
    price: 2499,
    originalPrice: 3199,
    rating: 4.4,

    description: "A lightweight fitness tracker with step and sleep tracking.",
    highlights: ["Heart Rate Monitor", "Sleep Tracking", "Waterproof"],
    features: ["OLED Display", "Call and Message Alerts", "Long Battery Life"],
    category: "Wearables",
  },
  {
    name: "Wireless Mouse JKL",
    images: [
      "https://img.freepik.com/free-photo/red-computer-mouse_1260-13.jpg",
      "https://img.freepik.com/free-photo/purple-computer-mouse_1260-11.jpg",
      "https://img.freepik.com/free-vector/mouse_24908-54360.jpg",
    ],
    price: 799,
    originalPrice: 999,
    rating: 4.5,

    description: "A wireless mouse with adjustable DPI and ergonomic design.",
    highlights: ["Adjustable DPI", "2.4GHz Wireless", "Ergonomic Design"],
    features: ["Silent Clicks", "Long Battery Life", "Compact Size"],
    category: "Peripherals",
  },
  {
    name: "Digital Camera MNO",
    images: [
      "https://img.freepik.com/free-photo/photo-camera-still-life_23-2150630950.jpg",
      "https://img.freepik.com/free-photo/mid-section-woman-holding-digital-camera_107420-96191.jpg",
      "https://img.freepik.com/free-photo/mid-section-woman-holding-digital-camera_107420-96191.jpg",
    ],
    price: 22999,
    originalPrice: 26999,
    rating: 4.4,

    description: "A high-quality digital camera with full HD video recording.",
    highlights: ["24MP", "Full HD Video", "Wi-Fi"],
    features: [
      "Optical Image Stabilization",
      "Touchscreen Display",
      "Interchangeable Lens",
    ],
    category: "Cameras",
  },
  {
    name: "Noise-Cancelling Earbuds PQR",
    images: [
      "https://img.freepik.com/free-photo/blonde-girl-blue-sweatshirt-taking-out-headphones-hear-people-around_114579-27191.jpg",
      "https://img.freepik.com/free-photo/blonde-girl-blue-sweatshirt-wearing-headphones-enjoying-music-having-fun_114579-27195.jpg",
      "https://img.freepik.com/free-photo/blonde-girl-blue-sweatshirt-wearing-headphones-trying-understand-music_114579-27232.jpg",
    ],
    price: 5499,
    originalPrice: 6999,
    rating: 4.7,

    description:
      "Wireless noise-cancelling earbuds with superior sound quality.",
    highlights: [
      "Active Noise Cancellation",
      "20 Hours Playback",
      "Fast Charging",
    ],
    features: ["IPX5 Waterproof", "Touch Controls", "Bluetooth 5.0"],
    category: "Audio",
  },
  {
    name: "Smartphone XYZ",
    images: [
      "https://img.freepik.com/free-photo/smartphones-city-concept_23-2150246080.jpg",
      "https://img.freepik.com/free-photo/elegant-smartphone-composition_23-2149437107.jpg",
      "https://img.freepik.com/free-photo/elegant-smartphone-composition_23-2149437084.jpg",
    ],
    price: 14999,
    originalPrice: 19999,
    rating: 4.5,
    description: "A powerful smartphone with the latest technology.",
    highlights: ["4GB RAM", "128GB Storage", "5000mAh Battery", "Dual SIM"],
    features: [
      "Octa-core Processor",
      "Super AMOLED Display",
      "Fast Charging",
      "5G Support",
    ],
    category: "Electronics",
  },
  {
    name: "Bluetooth Headphones ABC",
    images: [
      "https://img.freepik.com/free-photo/still-life-wireless-cyberpunk-headphones_23-2151072207.jpg",
      "https://img.freepik.com/free-photo/still-life-wireless-cyberpunk-headphones_23-2151072239.jpg",
      "https://img.freepik.com/free-photo/still-life-wireless-cyberpunk-headphones_23-2151072237.jpg",
    ],
    price: 1999,
    originalPrice: 2499,
    rating: 4.2,
    description:
      "Wireless headphones with superior sound and noise cancellation.",
    highlights: ["Noise Cancellation", "20 Hours Playback", "Bluetooth 5.0"],
    features: [
      "Over-ear Design",
      "Built-in Microphone",
      "Fast Charging",
      "Multipoint Connection",
    ],
    category: "Audio",
  },
  {
    name: "Smart TV DEF",
    images: [
      "https://img.freepik.com/free-photo/television-houseplants-room-scene-generative-ai_188544-12145.jpg",
      "https://img.freepik.com/free-psd/modern-tv-isolated_23-2151430326.jpg",
      "https://img.freepik.com/free-photo/landscape-nature-scene-tv-appliance-generative-ai_188544-12122.jpg",
    ],
    price: 24999,
    originalPrice: 29999,
    rating: 4.7,
    description: "A 4K Smart TV with crystal-clear display and Dolby audio.",
    highlights: ["4K UHD", "HDR10+", "Smart Features", "50-inch Display"],
    features: [
      "Built-in Chromecast",
      "Voice Assistant",
      "3 HDMI Ports",
      "Dolby Vision",
    ],
    category: "Home Entertainment",
  },
  {
    name: "Smartwatch GHI",
    images: [
      "https://img.freepik.com/free-photo/smartwatch-with-digital-assistant-arrangement_23-2149108009.jpg",
      "https://img.freepik.com/free-photo/active-woman-using-digital-device_53876-30638.jpg",
      "https://img.freepik.com/free-photo/technology-woman-checking-her-watch_144627-26201.jpg",
    ],
    price: 4499,
    originalPrice: 5999,
    rating: 4.3,
    description: "A fitness smartwatch with heart rate monitoring and GPS.",
    highlights: ["Heart Rate Monitor", "GPS", "1.4-inch Display", "Waterproof"],
    features: ["Customizable Watch Faces", "Music Control", "Step Tracking"],
    category: "Wearables",
  },
  {
    name: "Laptop JKL",
    images: [
      "https://img.freepik.com/free-photo/business-woman-presenting-laptop_23-2147626302.jpg",
      "https://img.freepik.com/free-photo/good-looking-business-woman-showing-laptop_23-2147626308.jpg",
      "https://img.freepik.com/free-psd/modern-businesswoman-presenting-laptop_23-2147632417.jpg",
    ],
    price: 49999,
    originalPrice: 54999,
    rating: 4.6,
    description:
      "A high-performance laptop for work, gaming, and entertainment.",
    highlights: [
      "16GB RAM",
      "512GB SSD",
      "Intel i7 Processor",
      "15.6-inch Display",
    ],
    features: ["Backlit Keyboard", "Wi-Fi 6", "Thunderbolt 3", "Slim Design"],
    category: "Computers",
  },
  {
    name: "Smart Door Lock MNO",
    images: [
      "https://img.freepik.com/free-photo/scanning-finger-coronavirus-contaminated-fingerprint-access-control_53876-95279.jpg",
      "https://img.freepik.com/free-photo/smart-home-tablet-wall_23-2149036895.jpg",
      "https://img.freepik.com/free-photo/man-using-tablet-his-smart-home_23-2149036902.jpg",
    ],
    price: 8499,
    originalPrice: 9999,
    rating: 4.4,
    description: "A secure smart door lock with fingerprint and app control.",
    highlights: ["Fingerprint Sensor", "App Control", "Tamper Alarm"],
    features: ["Auto Lock", "Remote Unlock", "Emergency Battery Backup"],
    category: "Smart Home",
  },
  {
    name: "Gaming Chair PSR",
    images: [
      "https://img.freepik.com/free-photo/still-life-seat-gamers_23-2149746585.jpg",
      "https://img.freepik.com/free-photo/gaming-setup-with-neon-light_23-2149829125.jpg",
      "https://img.freepik.com/free-photo/high-angle-gaming-controller-chair_23-2149829127.jpg",
    ],
    price: 11999,
    originalPrice: 12999,
    rating: 4.5,
    description:
      "An ergonomic gaming chair designed for comfort during long sessions.",
    highlights: [
      "Reclining Backrest",
      "Adjustable Armrests",
      "Memory Foam Padding",
    ],
    features: ["360-degree Swivel", "Lumbar Support", "Leather Finish"],
    category: "Furniture",
  },
  {
    name: "Blender STU",
    images: [
      "https://img.freepik.com/free-photo/smiling-young-woman-preparing-paper-pulp-blender_23-2147845499.jpg",
      "https://img.freepik.com/free-photo/woman-s-hand-grinding-paper-mixer-grinder_23-2147846089.jpg",
      "https://img.freepik.com/free-photo/midsection-view-woman-s-hand-putting-pieces-paper-blender_23-2147845548.jpg",
    ],
    price: 2199,
    originalPrice: 2999,
    rating: 4.3,
    description: "A versatile blender perfect for smoothies, sauces, and more.",
    highlights: ["500W Power", "2 Speed Settings", "Multi-Purpose Blades"],
    features: ["BPA-Free Jar", "Dishwasher Safe", "Compact Design"],
    category: "Kitchen Appliances",
  },
  {
    name: "Air Purifier VWX",
    images: [
      "https://img.freepik.com/free-photo/young-woman-using-home-technology_23-2149216656.jpg",
      "https://img.freepik.com/free-vector/realistic-digital-air-purifier-floor-cozy-room-vector-illustration_1284-70561.jpg",
      "https://img.freepik.com/free-photo/managing-smart-speakers-concept_23-2150170083.jpg",
    ],
    price: 9999,
    originalPrice: 12499,
    rating: 4.7,
    description: "An air purifier with HEPA filter for clean and fresh air.",
    highlights: ["HEPA Filter", "Auto Mode", "Silent Operation"],
    features: [
      "Real-Time Air Quality Indicator",
      "Filter Replacement Alerts",
      "Sleep Mode",
    ],
    category: "Home Appliances",
  },
  {
    name: "Coffee Maker XYZ",
    images: [
      "https://img.freepik.com/free-photo/view-process-making-pressed-coffee_23-2149709947.jpg",
      "https://img.freepik.com/free-photo/view-process-making-pressed-coffee_23-2149709946.jpg",
      "https://img.freepik.com/free-photo/tool-used-coffee-machine-coffee-making-process_23-2150187520.jpg",
    ],
    price: 4299,
    originalPrice: 5499,
    rating: 4.4,
    description: "A compact coffee maker with programmable brewing options.",
    highlights: ["1.2L Capacity", "Programmable Timer", "Auto Shut-off"],
    features: [
      "Removable Water Tank",
      "Brew Strength Selector",
      "Keep Warm Function",
    ],
    category: "Kitchen Appliances",
  },
  {
    name: "Smart Light Bulb ABC",
    images: [
      "https://img.freepik.com/free-photo/bulb-with-color-floating-inside_1112-282.jpg",
      "https://img.freepik.com/free-photo/bulb-turned-off_1112-283.jpg",
      "https://img.freepik.com/free-photo/bulb-with-colored-ink-inside_1112-156.jpg",
    ],
    price: 899,
    originalPrice: 1199,
    rating: 4.6,
    description:
      "A smart light bulb with customizable colors and voice control.",
    highlights: [
      "16 Million Colors",
      "App Control",
      "Voice Assistant Compatible",
    ],
    features: ["Energy Efficient", "Dimmable", "Schedules and Timers"],
    category: "Smart Home",
  },
  {
    name: "Electric Kettle DEF",
    images: [
      "https://img.freepik.com/free-photo/side-view-female-barista-grinding-coffee-beans_23-2148824471.jpg",
      "https://img.freepik.com/free-photo/male-barista-with-medical-mask-pouring-water-kettle_23-2148824379.jpg",
      "https://img.freepik.com/free-photo/front-view-male-barista-holding-kettle_23-2148824411.jpg",
    ],
    price: 1499,
    originalPrice: 1999,
    rating: 4.3,
    description: "A stainless steel electric kettle for fast boiling.",
    highlights: ["1.7L Capacity", "Auto Shut-off", "Boil-Dry Protection"],
    features: [
      "Cordless Operation",
      "360-degree Swivel Base",
      "Water Level Indicator",
    ],
    category: "Kitchen Appliances",
  },
  {
    name: "Fitness Tracker GHI",
    images: [
      "https://img.freepik.com/free-photo/young-woman-exercising-outdoor-what-i-need-while-jogging-is-good-music_329181-11177.jpg",
      "https://img.freepik.com/free-photo/young-woman-exercising-outdoor-woman-preparing-her-everyday-training_329181-11147.jpg",
      "https://img.freepik.com/free-photo/portrait-concentrated-young-fitness-woman-sportswear_171337-10062.jpg",
    ],
    price: 2499,
    originalPrice: 3199,
    rating: 4.4,
    description: "A lightweight fitness tracker with step and sleep tracking.",
    highlights: ["Heart Rate Monitor", "Sleep Tracking", "Waterproof"],
    features: ["OLED Display", "Call and Message Alerts", "Long Battery Life"],
    category: "Wearables",
  },
  {
    name: "Wireless Mouse JKL",
    images: [
      "https://img.freepik.com/free-photo/mouse-with-dripping-pink-paint_23-2148263684.jpg",
      "https://img.freepik.com/free-photo/top-view-blue-computer-mouse-with-yellow-background_23-2148226814.jpg",
      "https://img.freepik.com/free-photo/flat-lay-desk-concept-with-copy-space_23-2148226932.jpg",
    ],
    price: 799,
    originalPrice: 999,
    rating: 4.5,
    description: "A wireless mouse with adjustable DPI and ergonomic design.",
    highlights: ["Adjustable DPI", "2.4GHz Wireless", "Ergonomic Design"],
    features: ["Silent Clicks", "Long Battery Life", "Compact Size"],
    category: "Peripherals",
  },
  {
    name: "Digital Camera MNO",
    images: [
      "https://img.freepik.com/free-photo/artificial-black-camera-blue-background_23-2148188202.jpg",
      "https://img.freepik.com/free-photo/front-view-photographer-with-camera_23-2150630630.jpg",
      "https://img.freepik.com/free-photo/photo-camera-still-life_23-2150630950.jpg",
    ],
    price: 22999,
    originalPrice: 26999,
    rating: 4.4,
    description: "A high-quality digital camera with full HD video recording.",
    highlights: ["24MP", "Full HD Video", "Wi-Fi"],
    features: [
      "Optical Image Stabilization",
      "Touchscreen Display",
      "Interchangeable Lens",
    ],
    category: "Cameras",
  },
  {
    name: "Noise-Cancelling Earbuds PQR",
    images: [
      "https://img.freepik.com/free-photo/vertical-shot-tired-sportswoman-has-pain-neck-keeps-eyes-closed-has-combed-curly-hair-dressed-beige-activewear-wears-stereo-headphones-ears-listens-music-poses-outdoors-stadium_273609-62228.jpg",
      "https://img.freepik.com/free-photo/woman-has-sweat-after-intensive-cardio-training-takes-break-drinks-refreshing-water-from-bottle-dressed-sportswear-listens-motivational-music_273609-55216.jpg",
      "https://img.freepik.com/free-photo/sporty-thoughtful-woman-with-curly-hair-listens-audio-track-wireless-headphones-touches-neck-concentrated-down-takes-break-after-workout_273609-55587.jpg",
    ],
    price: 5499,
    originalPrice: 6999,
    rating: 4.7,
    description:
      "Wireless noise-cancelling earbuds with superior sound quality.",
    highlights: [
      "Active Noise Cancellation",
      "20 Hours Playback",
      "Fast Charging",
    ],
    features: ["IPX5 Waterproof", "Touch Controls", "Bluetooth 5.0"],
    category: "Audio",
  },
  {
    name: "Vacuum Cleaner STU",
    images: [
      "https://img.freepik.com/free-photo/man-servant-doing-chores-around-house_23-2149508160.jpg",
      "https://img.freepik.com/free-photo/man-doing-professional-home-cleaning-service_23-2150358990.jpg",
      "https://img.freepik.com/free-photo/man-doing-professional-home-cleaning-service_23-2150358991.jpg",
    ],
    price: 6999,
    originalPrice: 8999,
    rating: 4.6,
    description: "A powerful vacuum cleaner with advanced suction technology.",
    highlights: ["High Suction Power", "Bagless", "HEPA Filter"],
    features: ["Cord Rewind", "Multiple Attachments", "Lightweight Design"],
    category: "Home Appliances",
  },
  {
    name: "Water Purifier GHI",
    images: [
      "https://img.freepik.com/free-vector/smart-fridge-gas-oven-hood-kitchen-appliances_107791-2971.jpg",
      "https://img.freepik.com/free-vector/cartoon-water-filter_1284-71880.jpg",
      "https://img.freepik.com/free-vector/dishwasher-machine-realistic-set-three-isolated-images-with-different-views-dish-washing-machine-vector-illustration_1284-67999.jpg",
    ],
    price: 12999,
    originalPrice: 15999,
    rating: 4.7,
    description: "A smart water purifier with UV and RO filtration.",
    highlights: ["UV + RO", "7L Storage", "Real-Time TDS Monitoring"],
    features: ["Auto Shut-off", "Filter Change Alert", "Wall Mountable"],
    category: "Home Appliances",
  },
  {
    name: "Smart Thermostat ABC",
    images: [
      "https://img.freepik.com/free-photo/full-shot-smiley-woman-pushing-heater-s-red-button_23-2149395837.jpg",
      "https://img.freepik.com/free-photo/close-up-finger-using-vitroceramic-app_23-2148994136.jpg",
      "https://img.freepik.com/free-photo/young-woman-using-home-technology_23-2149216635.jpg",
    ],
    price: 9999,
    originalPrice: 12999,
    rating: 4.5,
    description: "A smart thermostat that learns your schedule.",
    highlights: ["Energy Saving", "App Control", "Voice Assistant Compatible"],
    features: ["Auto-Schedule", "Remote Access", "Temperature Alerts"],
    category: "Smart Home",
  },
  {
    name: "Electric Toothbrush DEF",
    images: [
      "https://img.freepik.com/free-vector/electric-toothbush-poster_1284-21537.jpg",
      "https://img.freepik.com/free-vector/dental-banners-set-healthy-teeth_1284-32621.jpg",
      "https://img.freepik.com/free-vector/realistic-dental-care-brush_23-2149004605.jpg",
    ],
    price: 2499,
    originalPrice: 2999,
    rating: 4.3,
    description: "An advanced electric toothbrush for a thorough clean.",
    highlights: ["2-Minute Timer", "Pressure Sensor", "Rechargeable Battery"],
    features: ["Multiple Brush Heads", "Waterproof", "Travel Case"],
    category: "Personal Care",
  },
  {
    name: "Hair Dryer GHI",
    images: [
      "https://img.freepik.com/free-photo/portrait-smiling-young-woman-dries-her-hair-gray_231208-1652.jpg",
      "https://img.freepik.com/free-photo/young-pretty-woman-holding-hair-dryer-straightening-isolated-white_231208-1636.jpg",
      "https://img.freepik.com/free-photo/young-woman-drying-long-hair-with-electric-fan-isolated-white_231208-1661.jpg",
    ],
    price: 1999,
    originalPrice: 2499,
    rating: 4.4,
    description: "A powerful hair dryer with ionic technology.",
    highlights: ["Ionic Conditioning", "3 Heat Settings", "Cool Shot"],
    features: ["Foldable Handle", "Concentrator Nozzle", "Lightweight Design"],
    category: "Personal Care",
  },
  {
    name: "Smart Plug MNO",
    images: [
      "https://img.freepik.com/free-vector/amourous-bright-love-poster-with-realistic-glowing-plugged-electric-light-bulb-heart-shape_1284-49298.jpg",
      "https://img.freepik.com/free-vector/realistic-romantic-concept-realistic-wired-light-bulb-heart-shape-with-plug-socket-isolated_1284-49295.jpg",
      "https://img.freepik.com/free-vector/realistic-wired-lamp_1284-50250.jpg",
    ],
    price: 1499,
    originalPrice: 1999,
    rating: 4.6,
    description: "A Wi-Fi-enabled smart plug for remote control of appliances.",
    highlights: ["App Control", "Voice Assistant Compatible", "Energy Monitor"],
    features: ["Timer and Schedule", "Compact Design", "Easy Setup"],
    category: "Smart Home",
  },
  {
    name: "Robot Vacuum STU",
    images: [
      "https://img.freepik.com/free-photo/still-life-robotic-vacuum_23-2151108362.jpg",
      "https://img.freepik.com/free-photo/still-life-robotic-vacuum_23-2151108356.jpg",
      "https://img.freepik.com/free-photo/still-life-robotic-vacuum_23-2151108320.jpg",
    ],
    price: 24999,
    originalPrice: 29999,
    rating: 4.8,
    description: "A robotic vacuum cleaner with smart navigation.",
    highlights: ["Automatic Docking", "Multi-Surface Cleaning", "App Control"],
    features: ["Scheduling", "HEPA Filter", "Low Noise"],
    category: "Smart Home",
  },
  {
    name: "Steam Iron DEF",
    images: [
      "https://img.freepik.com/free-photo/young-woman-ironing-clothes_144627-42934.jpg",
      "https://img.freepik.com/free-photo/young-woman-ironing-clothes_144627-42933.jpg",
      "https://img.freepik.com/free-photo/female-smoothing-out-wrinkles-washed-shirt_259150-58948.jpg",
    ],
    price: 1799,
    originalPrice: 2499,
    rating: 4.4,
    description: "A steam iron with advanced wrinkle-removal technology.",
    highlights: ["Non-Stick Soleplate", "Auto Shut-off", "Variable Steam"],
    features: ["Vertical Steam", "Self-Clean Function", "Lightweight Design"],
    category: "Home Appliances",
  },
  {
    name: "Washing Machine PQR",
    images: [
      "https://img.freepik.com/free-vector/washing-machine-realistic-poster-with-quiet-quick-wash-symbols-illustration_1284-29131.jpg",
      "https://img.freepik.com/free-photo/man-waiting-washing-machine-finish-its-program_23-2149117024.jpg",
      "https://img.freepik.com/free-photo/front-view-delighted-male-housekeeper-sitting-front-washer-laundry-basket-white-background_140725-112236.jpg",
    ],
    price: 22999,
    originalPrice: 26999,
    rating: 4.6,
    description: "A fully automatic washing machine with smart features.",
    highlights: ["6kg Capacity", "Inverter Motor", "Smart Diagnosis"],
    features: ["Quick Wash", "Child Lock", "Water Level Sensor"],
    category: "Home Appliances",
  },
  {
    name: "Dishwasher ABC",
    images: [
      "https://img.freepik.com/free-photo/front-view-young-male-with-green-basket-full-clothes-holding-bank-card-white-wall_140725-107853.jpg",
      "https://img.freepik.com/free-photo/front-view-young-male-with-green-basket-full-clothes-holding-bank-card-white-wall_140725-107850.jpg",
      "https://img.freepik.com/free-photo/front-view-young-male-washing-clothes-with-help-washing-machine-white-wall_140725-107813.jpg",
    ],
    price: 34999,
    originalPrice: 39999,
    rating: 4.7,
    description: "An energy-efficient dishwasher with multiple wash programs.",
    highlights: ["12 Place Settings", "Eco Mode", "Quick Wash"],
    features: ["Delay Start", "Rinse Aid Indicator", "Adjustable Racks"],
    category: "Home Appliances",
  },
  {
    name: "Soundbar GHI",
    images: [
      "https://img.freepik.com/free-photo/view-horizontal-bluetooth-speaker-with-simple-minimal-modern-design_23-2150807998.jpg",
      "https://img.freepik.com/free-photo/high-angle-smart-speaker-home_23-2150171767.jpg",
      "https://img.freepik.com/free-photo/speakers-with-extremely-high-volume-desk_23-2149625153.jpg",
    ],
    price: 11999,
    originalPrice: 14999,
    rating: 4.5,
    description: "A sleek soundbar with virtual surround sound.",
    highlights: ["Bluetooth", "Dolby Audio", "Wireless Subwoofer"],
    features: ["Multiple Inputs", "Wall Mountable", "Remote Control"],
    category: "Audio",
  },
  {
    name: "Action Camera JKL",
    images: [
      "https://img.freepik.com/free-photo/vintage-young-man-filming_1368-6211.jpg",
      "https://img.freepik.com/free-photo/vintage-young-man-filming_1368-6211.jpg",
      "https://img.freepik.com/free-photo/young-man-with-retro-camera_155003-560.jpg",
    ],
    price: 15999,
    originalPrice: 19999,
    rating: 4.6,
    description: "A compact action camera with 4K recording capabilities.",
    highlights: ["4K UHD", "Waterproof", "Wide-Angle Lens"],
    features: ["Image Stabilization", "Touchscreen", "Voice Control"],
    category: "Cameras",
  },
  {
    name: "Portable Speaker MNO",
    images: [
      "https://img.freepik.com/free-photo/man-using-smart-speaker_23-2149036847.jpg",
      "https://img.freepik.com/free-photo/man-using-smart-speaker_23-2149036846.jpg",
      "https://img.freepik.com/free-photo/man-using-smart-speaker_23-2149036843.jpg",
    ],
    price: 2999,
    originalPrice: 3999,
    rating: 4.5,
    description: "A portable Bluetooth speaker with deep bass.",
    highlights: ["Waterproof", "10 Hours Battery", "Bluetooth 5.0"],
    features: ["Built-in Microphone", "Stereo Pairing", "Compact Design"],
    category: "Audio",
  },
  {
    name: "Electric Shaver STU",
    images: [
      "https://img.freepik.com/free-photo/portrait-happy-smiling-bearded-man-showing-electric-razor_171337-17302.jpg",
      "https://img.freepik.com/free-photo/man-doing-his-self-care-ritual_23-2149204946.jpg",
      "https://img.freepik.com/free-photo/portrait-young-man-trimming-his-beard-with-trimmer_23-2148213365.jpg",
    ],
    price: 3499,
    originalPrice: 4499,
    rating: 4.3,
    description: "An electric shaver for a smooth and close shave.",
    highlights: ["Wet & Dry", "Rechargeable Battery", "Precision Trimmer"],
    features: ["Rotary Blades", "Easy Clean", "Ergonomic Grip"],
    category: "Personal Care",
  },
  {
    name: "Smart Speaker XYZ",
    images: [
      "https://img.freepik.com/free-photo/high-angle-smart-speaker-home_23-2150171756.jpg",
      "https://img.freepik.com/free-photo/high-angle-smart-speaker-home_23-2150171755.jpg",
      "https://img.freepik.com/free-photo/high-angle-smart-speaker-home_23-2150171754.jpg",
    ],
    price: 4999,
    originalPrice: 6499,
    rating: 4.6,
    description: "A voice-controlled smart speaker with high-quality sound.",
    highlights: ["Voice Assistant", "Bluetooth", "Multi-Room Audio"],
    features: ["Far-Field Microphones", "Compact Design", "360-Degree Sound"],
    category: "Smart Home",
  },
  {
    name: "Gaming Mouse ABC",
    images: [
      "https://img.freepik.com/free-photo/view-neon-illuminated-gaming-desk-setup-with-keyboard_23-2149529362.jpg",
      "https://img.freepik.com/free-photo/view-illuminated-neon-gaming-keyboard-setup-controller_23-2149529368.jpg",
      "https://img.freepik.com/free-photo/view-neon-illuminated-gaming-desk-setup-with-keyboard_23-2149529359.jpg",
    ],
    price: 2499,
    originalPrice: 2999,
    rating: 4.7,
    description: "A high-performance gaming mouse with customizable DPI.",
    highlights: ["RGB Lighting", "Programmable Buttons", "Ergonomic Design"],
    features: ["Adjustable Weights", "Precision Sensor", "Long Cable"],
    category: "Peripherals",
  },
  {
    name: "Smart Doorbell DEF",
    images: [
      "https://img.freepik.com/free-photo/people-interacting-with-ai-their-daily-lives_23-2151870994.jpg",
      "https://img.freepik.com/free-photo/young-woman-presses-button-intercom_641386-184.jpg",
      "https://img.freepik.com/free-photo/medium-shot-woman-wearing-mask_23-2148767173.jpg",
    ],
    price: 7999,
    originalPrice: 9999,
    rating: 4.5,
    description: "A smart doorbell with HD video and motion detection.",
    highlights: ["HD Video", "Two-Way Audio", "Night Vision"],
    features: ["App Notifications", "Video Recording", "Weather Resistant"],
    category: "Smart Home",
  },
  {
    name: "Induction Cooktop GHI",
    images: [
      "https://img.freepik.com/free-photo/woman-preparing-rigatoni-pasta-saucepan_23-2147893591.jpg",
      "https://img.freepik.com/free-photo/close-up-woman-preparing-pasta-kitchen-counter_23-2147893396.jpg",
      "https://img.freepik.com/free-photo/smiling-woman-preparing-food-holding-digital-tablet_23-2147893598.jpg",
    ],
    price: 2999,
    originalPrice: 3999,
    rating: 4.4,
    description: "A portable induction cooktop with multiple cooking modes.",
    highlights: ["Touch Controls", "Preset Menus", "Auto Shut-off"],
    features: ["Timer Function", "Energy Efficient", "Compact Design"],
    category: "Kitchen Appliances",
  },
  {
    name: "Smart Security Camera JKL",
    images: [
      "https://img.freepik.com/free-photo/view-round-modern-webcam-with-shadows-background_23-2150808001.jpg",
      "https://img.freepik.com/free-psd/cctv-security-template-design_23-2151461452.jpg",
      "https://img.freepik.com/free-photo/view-round-modern-webcam-with-shadows-background_23-2150808004.jpg",
    ],
    price: 6499,
    originalPrice: 7999,
    rating: 4.6,
    description:
      "A smart security camera with cloud storage and motion alerts.",
    highlights: ["Full HD Video", "Motion Detection", "Night Vision"],
    features: ["Two-Way Audio", "Cloud Storage", "Remote Access"],
    category: "Smart Home",
  },
];

function seed() {
  Product.insertMany(arr)
    .then(() => {
      console.log("DB seeded");
    })
    .catch((err) => {
      console.log("ERROR");
      console.log(err.message);
    });
}

module.exports = seed;
